version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=dronerentDB
      - DB_USER=postgres
      - DB_PASSWORD=root
    volumes:
      - .:/code
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:13.15
    environment:
      - POSTGRES_DB=dronerentDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
