# Generated by Django 5.0.7 on 2024-07-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='drone',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='drone',
            name='brand',
            field=models.CharField(choices=[('DJI', 'DJI'), ('Parrot', 'Parrot'), ('Yuneec', 'Yuneec'), ('Autel', 'Autel')], max_length=100),
        ),
        migrations.AlterField(
            model_name='drone',
            name='category',
            field=models.CharField(choices=[('Consumer', 'Consumer'), ('Professional', 'Professional'), ('Racing', 'Racing')], max_length=100),
        ),
        migrations.AlterField(
            model_name='drone',
            name='model',
            field=models.CharField(max_length=100),
        ),
    ]
