# Generated by Django 5.0.7 on 2024-07-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_drone_availability_drone_price_per_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
